version: "3"
includes:
  fmt: ./scripts/fmt.yml
  lint: ./scripts/lint.yml
  log: ./scripts/log.yml
  enter: ./scripts/enter.yml
  db: ./scripts/db.yml
tasks:
  deploy:
    desc: Deploy to target machine
    cmds:
      - ./scripts/ci/deploy.sh
  log:
    desc: Log all container with merged streams
    cmds:
      - docker compose logs -f
  lint:
    desc: Lint all files
    cmds:
      - task: lint:sh
      - task: lint:ansible
      - task: lint:docker
  fmt:
    desc: Format all files
    cmds:
      - task: fmt:sh
      - task: fmt:dotnet
      - task: fmt:yaml
      - task: fmt:nix
      - task: fmt:md
  cfg:scripts:
    cmds:
      - chmod -R +x ./scripts

  setup:
    desc: Setup required docker volumes for development
    cmds:
      - docker volume create pitapairing-db-data
      
  dev:
    watch: true
    desc: Start development mode
    sources:
      - "**/*.cs"
    cmds:
      - task: start
  start:
    desc: Starts development server
    cmds:
      - docker compose up -d --build
  stop:
    desc: Stops development server
    cmds:
      - docker compose down
